services:
  bridge-db:
    image: postgres:14
    container_name: bridge-db
    ports:
      - "5400:5432"
    restart: always
    command:
      [
        "postgres",
        "-c", "shared_preload_libraries=pg_stat_statements",
        "-c", "max_connections=1000"
      ]
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: bridge_user
      POSTGRES_DB: postgres
      PGDATA: /postgresql/data
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - bridge_db_volume:/postgresql/data

  acc-chain-bridge:
    image: bosagora/acc-bridge-validator:v2.x.x-e5aaf9
    container_name: acc-chain-bridge
    restart: always
    volumes:
      - ./config:/app/config
    env_file:
      - ./.chain-bridge.env
    depends_on:
      - bridge-db

  acc-loyalty-bridge:
    image: bosagora/acc-bridge-validator:v2.x.x-e5aaf9
    container_name: acc-loyalty-bridge
    restart: always
    volumes:
      - ./config:/app/config
    env_file:
      - ./.loyalty-bridge.env
    depends_on:
      - bridge-db

volumes:
  bridge_db_volume:
